### ISSUE TITLE
Missing string_view literals

### ISSUE THREAD

**Issue by willwray** [tcbrindle/cpp17_headers#10]
I miss them, literally.

cppreference [std::literals::string_view_literals::operator""sv](http://en.cppreference.com/w/cpp/string/basic_string_view/operator%22%22sv)

**Comment by willwray** [comment]
Seems to be missing in boost too (at least I can't find it).
The literal operator is important because it is constexpr.
Without it there is no way to get a constexpr `string_view("literal")`
(other than creating a constexpr templated `make_string_view(const char (&cstr)[N])`)

One problem is that compilers will warn on reserved `sv` identifier:
eg, gcc
>`warning: literal operator suffixes not preceded by '_' are reserved for future standardization [-Wliteral-suffix]`

With gcc the warning can be silenced by surrounding the code with a `#pragma`:

    namespace stx{ namespace string_view_literal {
    
    #pragma GCC diagnostic ignored "-Wliteral-suffix"

    constexpr string_view operator ""sv(char const* str, std::size_t len) noexcept {
        return {str, len};
    }

    #pragma GCC diagnostic pop

    } }

    using namespace boost::string_view_literal;
    constexpr auto sv = "sv"sv;
    constexpr auto vs = "sv"sv;
    static_assert(sv.data() == vs.data(), "same literal, different id");

**Comment by tcbrindle** [comment]
The problem is that using `sv` as a literal suffix without the leading underscore is undefined behaviour -- and while you can "get away with it" by silencing the warning as you've pointed out, I'm really not keen on breaking the rules by adding it to the library. Presumably Boost omits it for the same reason.

What we could theoretically do is introduce a `_sv` literal operator (with a leading underscore), say in an inline namespace `stx::literals`. However, this is obviously incompatible with the "real" standard library literal, and would mean that one can no longer upgrade from `stx::string_view` to `std::string_view` in future simply by changing the namespace.

On the other hand, for users who really want a `string_view` literal, it's easy to define one yourself, as you've done above. This would keep working even after doing `s/stx/std` when moving to C++17.

So I'm not really sure of the best way to proceed. Any thoughts?

**Comment by willwray** [comment]
Yes, on reflection the situation is messier than I'd realised for 3rd party backports.

Even with backported `string_view` and `sv` other library parts are missing `sting_view` interface.
Vocabulary types like this are 'viral' so standalone usage is going to be limited.

The best solution would be compiler extensions providing standard-compliant backports.
Given the virality, though, this would have to extend to many parallel headers and their implementations.

Boost is open to accepting a PR for `_sv` literal (no reason not to) but `sv` is a no-no
(From discussion on cpplang slack #boost channel this morning).
>marshall
>libc++ supports string_view back to C++98 (as an extension), but the literals only exist in C++14 and later.
>But boost::string_view works everywhere (not just in clang).  But no literals.
>I like the idea of adding literals - but it will have to be `_sv`

(No one said whether omission from boost was an oversight or deliberate sidestep of the issues.)
(I'm not sure why libc++  literals are C++14 vs C++11 - constexpr support perhaps.)

I suggested adding both `_sv` and `sv`:
>How about boost providing both `_sv` and `sv` (with a disclaimer) in different namespaces?
>Standard-compliant-yet-non-standard `_sv` could go in non-standard `string_view_literal` namespace.
>Non-standard-compliant-yet-standard `sv` could go in standard-shadowing namespace `string_view_literals`

This didn't wash for boost but could be appropriate for a standalone repo like this.
What do you think?

Otherwise, maybe at least include the code in the documentation, with disclaimers.
Users can then cut and paste into their code at their own peril, with warning of pros & cons.

**Comment by tcbrindle** [comment]
> Boost is open to accepting a PR for _sv literal (no reason not to) but sv is a no-no

I'm afraid adding an `sv` literal is a no-go for me too. I'm happy to add a `_sv` though, if this would be useful.

**Comment by willwray** [comment]
I now believe that the std string_view literal operator `sv` is broken:
1. It is inconsistent with string_view design assumptions:
string_view's `char*` constructor acts (as if) to call `strlen` and scan for nul so we get:
`std::string_view{"a\0"}.size()==1`
It deliberately omits construction from char array.
string_view literal operator `sv` effectively constructs from char array up to the terminating nul, ignoring embedded nul chars.
`"a\0"sv.size()==2`
(I think that this should be raised as a defect of `sv`.)
2. It messes up backportability, due the naming issues discussed above.
3. Conformant c++17 now allows direct constexpr construction
`constexpr std::string_view sv = "sv";`
`constexpr auto vs = string_view{"vs"};`
so literals are less useful just for their constexpr-ness, as pre c++17
This c++17 snippet demonstrates the inconsistency (1.) at compile time
```
#include <string_view>
using namespace std::string_view_literals;

static_assert (std::string_view{"a\0"}.size()==1);
static_assert                 ("a\0"sv.size()==2);
```
So, I won't miss the missing string_view literal.
Adding a `_sv` literal has little use and big pitfalls.
The better solution is for a user to write a 'maker' function.
Let's close the issue.
