### ISSUE TITLE
Missing using for std::nullopt in the namespace

### ISSUE THREAD

**Issue by madscientist** [tcbrindle/cpp17_headers#3]
For implementations which have `<optional>` or `<experimental/optional>`, you need to add:

    using std::nullopt;

and

    using std::experimental::nullopt;

to the STX_NAMESPACE_NAME otherwise those aren't available in the right namespace.

**Comment by madscientist** [comment]
And the same for `std::in_place` and `std::experimental::in_place`; the type is imported with using but the actual value isn't.

**Comment by tcbrindle** [comment]
Hi, thanks for the bug report. I've committed a fix to master adding the using directives, would you mind giving it a try to see if it works for you?

**Comment by madscientist** [comment]
That worked, thanks.
